model_name_or_path: allenai/OLMo-2-1124-7B
use_flash_attn: true
tokenizer_name: allenai/OLMo-2-1124-7B
use_slow_tokenizer: false
dataset_mixer:
    allenai/tulu-3-sft-olmo-2-mixture: 1.0

max_seq_length: 4096
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 4 # effective batch size 128 with 4 nodes
learning_rate: 1.0e-05
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
dataset_mix_dir: /output/
hf_metadata_dataset: allenai/olmo-instruct-evals
add_bos: true
